name: Build ecat

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Build
        run: |
          GOOS=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
          GOARCH=amd64
          mkdir -p bin
          go build -o bin/ecat-$GOOS-$GOARCH cmd/main.go

      - name: Archive binary
        run: |
          mkdir -p dist
          tar -czf dist/ecat-$GOOS-$GOARCH.tar.gz -C bin ecat-$GOOS-$GOARCH

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ecat-$GOOS-$GOARCH
          path: dist/ecat-$GOOS-$GOARCH.tar.gz
